version: 2.1

executors:
  circle-jdk-executor:
    working_directory: ~/micrometer
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
    resource_class: medium+
    docker:
      - image: cimg/openjdk:21.0.2
  machine-executor:
    working_directory: ~/micrometer
    machine:
      image: ubuntu-2204:2024.05.1

commands:
  gradlew-build:
    description: 'Run a Gradle build using the wrapper'
    parameters:
      command:
        type: string
        default: 'build'
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: downloadDependencies
          command: ./gradlew downloadDependencies --console=plain
      - save_cache:
          key: gradle-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.gradle
      - run:
          name: run gradle command
          command: ./gradlew << parameters.command >>
      - run:
          name: collect test reports
          when: always
          command: |
            mkdir -p ~/micrometer/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/micrometer/test-results/junit/ \;
      - store_test_results:
          path: ~/micrometer/test-results/
      - store_artifacts:
          path: ~/micrometer/test-results/

jobs:
  build:
    executor: circle-jdk-executor
    steps:
      - gradlew-build
      - run: ./gradlew shenandoahTest
      - run: ./gradlew zgcTest
      - run: ./gradlew zgcGenerationalTest

  docker-tests:
    executor: machine-executor
    steps:
      - run: sudo apt -y update && sudo apt -y install openjdk-21-jdk
      - gradlew-build:
          command: dockerTest

  deploy:
    executor: circle-jdk-executor
    steps:
      - checkout
      - restore_cache:
          key: gradle-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Deployment
          command: sh ./gradle/deploy.sh

workflows:
  version: 2
  build_prs_deploy_snapshots:
    jobs:
      - build
      - docker-tests
      - deploy:
          requires:
            - build
            - docker-tests
          filters:
            branches:
              only:
                - main
                - /\d+\.\d+\.x/
  build_deploy_releases:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
      - docker-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
      - deploy:
          requires:
            - build
            - docker-tests
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+(-(RC|M)\d+)?$/
